# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  version: v1.0.1

pool:
  # name: Default
  name: Azure Pipelines

steps:
- checkout: self
- checkout: git://gitops
  persistCredentials: true
  fetchDepth: 0


- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "piotr.minkowski@gmail.com"
      git config --global user.name "Piotr Minkowski"
      cd gitops
      git checkout main
      yq e '.image.tag = "$(version)"' -i apps/basic/test/values.yaml
      cat apps/basic/test/values.yaml
      git add apps/basic/test/values.yaml
      git commit -m "$(version)"
      git remote -v
      git push https://$(System.AccessToken)@dev.azure.com/pminkows/pminkows/_git/gitops main
  displayName: List catalog
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    
# - task: CmdLine@2
#   inputs:
#     script: 'oc login https://172.30.0.1:443 -u kubeadmin -p $(OCP_PASSWORD) --insecure-skip-tls-verify=true'
#   displayName: Login to OpenShift
# - task: CmdLine@2
#   inputs:
#     script: 'oc project myapp'
#   displayName: Switch to project
# - task: CmdLine@2
#   inputs:
#     script: 'oc process -f ocp/ci.yaml -o yaml -p IMAGE_TAG=v1.0-$(Build.BuildId) -p NAMESPACE=myapp -p BUILDER_IMAGE=ubi8-openjdk-21:1.18 | oc apply -f -'
#   displayName: Create build
# - task: CmdLine@2
#   inputs:
#     script: 'oc start-build sample-spring-boot-web-bc -w'
#     failOnStderr: true
#   displayName: Start build
#   timeoutInMinutes: 5
# - task: vsix-argocd-task@1
#   inputs:
#     ArgoCDService: 'argocd'
#     argocdApplication: '{ Value : "sample-spring-boot-web-test", DisplayValue : "sample-spring-boot-web-test" }'
#     argocdCommand: 'sync'
